import "./globals.css";

// import "flowbite/dist/flowbite";

import Navbar from "@/components/navbar/Navbar";
import HeadInfos from "@/components/navbar/HeadInfos";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased bg-main-bg`}>
        {/* HeadInfos component */}
        <HeadInfos />
        <div className="sticky top-0  z-50   min-h-screen ">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
